Remove dependency of DirectX SDK
GPUOpen-Tools/amd_tootle pull request #18
Opened 2017-04-30 13:05 UTC by PooyaEimandar

Remove dependency of DirectX SDK June 2010 and integrate it with DirectX SDK of Windows 8/8.1/10

2017-05-01 17:56 UTC, bpurnomo commented
Hi PooyaEimandar,
  Thank you for contributing this PR.  Could you please update the PR with the following?
1. Fix the whitespacing issue. Use 4 spaces instead of tab.
2. Remove the inclusion of Microsoft DirectXMesh files directly in this PR.  I will include DirectXMesh files indirectly by cloning the DirectXMesh repository.  I can make this part of change.

Once the two issues above are fixed in this PR, I will accept it.

2017-05-02 12:03 UTC, PooyaEimandar commented
Hi Budi Purnomo
I just fixed it, kindly include DirectXMesh files indirectly by cloning the DirectXMesh repository.
Thanks in advance.

2017-05-04 13:59 UTC, bpurnomo requested changes
Hi,
  I have a chance to try and review in depth your PR.  Please see below for my detailed comments.

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/RayTracer/makefile
> +CC      = g++ -O3 -fpermissive -msse -D_SOFTWARE_ONLY_VERSION -D_LINUX
Please revert all the changes in this file as makefiles do require TAB instead of spaces.

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/TootlePCH.h
> +#ifdef _WIN_8_1_SDK
Should this line be using _DX11_1_ define?

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/clustering.cpp
> +#endif
Could you use the original debugf macro?  The same review comment applies for the same changes in other files.

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/clustering.cpp
> +#ifdef _DX11_1_
Please remove

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/d3doverdrawwindow.cpp
> +#ifdef _DX11_1_
Please remove

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/d3doverdrawwindow.cpp
> +#ifdef _DX11_1_
Please remove

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/d3doverdrawwindow.cpp
> +#ifdef _DX11_1_
Please remove

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/d3doverdrawwindow.cpp
> +                auto _xmv = DirectX::XMVectorSet(v[0], v[1], v[2], 0);
Try not to prefix variable names with "_" character as this naming convention should applies to system variable names.

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/error.h
> +#ifdef _DX11_1_
Could we use the original macros?

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/makefile
> +CC      = g++ -fpermissive -msse -D_SOFTWARE_ONLY_VERSION -D_LINUX
Please revert all the changes in this file as makefiles do require TAB instead of spaces.

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/mesh.h
> +#ifdef _DX11_1_
Please remove

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/mesh.h
> +#ifdef _DX11_1_
Please remove

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleLib/mesh.h
> +#ifdef _DX11_1_
Please remove

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleSample/Tootle.cpp
> +    settings.algorithmChoice       = TOOTLE_FAST_OPTIMIZE;
Please revert to the original setting.

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleSample/Tootle.cpp
> +    //ParseCommandLine(argc, argv, &settings);
Please revert to the original as this change is only relevant for your local use.

2017-05-04 13:59 UTC, bpurnomo commented on src/TootleSample/makefile
> +CC      = g++ -D_SOFTWARE_ONLY_VERSION -D_LINUX
Please revert all changes in this file

2017-05-06 13:06 UTC, PooyaEimandar commented
Hi 
I just fixed it.

2017-05-06 13:19 UTC, PooyaEimandar commented
I reverted error.h to original source. but there were some errors with debugf.
`Error	C2143	syntax error: missing ';' before 'string'	TootleLib	c:\users\dfm\documents\github\pooyaeimandar\amd-tootle\src\tootlelib\mesh.h`
 Could you please check it?

2017-05-08 22:09 UTC, bpurnomo requested changes
See my code review here for how to fix the errors with debugf in mesh.h file.

2017-05-08 22:09 UTC, bpurnomo commented on src/TootleLib/mesh.h
> +    debugf("Done in %gs", time.GetElapsed());
This line is missing an extra opening and closing parentheses.

2017-05-08 22:09 UTC, bpurnomo commented on src/TootleLib/mesh.h
> +    debugf("Done in %gs", time.GetElapsed());
This line is missing an extra opening and closing parentheses.

2017-05-08 22:09 UTC, bpurnomo commented on src/TootleLib/mesh.h
> +    debugf("Done in %gs", time.GetElapsed());
This line is missing an extra opening and closing parentheses.

2017-05-13 06:05 UTC, PooyaEimandar commented
Thanks for code review. 
I just fixed it.

2017-05-17 11:33 UTC, bpurnomo commented
Thank you.  This PR will be merged together with the change to include DirectXMesh repo.

2017-05-17 11:33 UTC, bpurnomo approved these changes

2017-05-17 12:17 UTC, PooyaEimandar commented
You're welcome.

2017-06-22 18:19 UTC, merged